prestamos_index:
    path:     /bitacora
    defaults: { _controller: "LaFuentePrestamoBundle:Prestamo:index" }
    methods:  GET

prestamos_devolucion:
    path:     /{prestamo}/devolucionTotal
    defaults: { _controller: "LaFuentePrestamoBundle:Prestamo:devolucionTotal" }
    methods:  GET

prestamos_devolucion_parcial:
    path:     /devolucionParcial
    defaults: { _controller: "LaFuentePrestamoBundle:Prestamo:devolucionParcial" }
    methods:  [POST, GET]
