producto_termo_index:
    path:     /
    defaults: { _controller: "LaFuentePrestamoBundle:Termo:index" }
    methods:  [GET, POST]

producto_termo_show:
    path:     /{id}/show
    defaults: { _controller: "LaFuentePrestamoBundle:Termo:show" }
    methods:  GET

producto_termo_edit:
    path:     /{id}/edit
    defaults: { _controller: "LaFuentePrestamoBundle:Termo:edit" }
    methods:  [GET, POST]

producto_termo_delete:
    path:     /{id}/delete
    defaults: { _controller: "LaFuentePrestamoBundle:Termo:delete" }
    methods:  GET
