<?php

namespace LaFuente\PrestamoBundle\Entity;

/**
 * BombillaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BombillaRepository extends ProductRepository
{

}
