<?php

namespace LaFuente\PrestamoBundle\Entity;

/**
 * MateRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MateRepository extends ProductRepository
{

}
