<?php

namespace LaFuente\PrestamoBundle\Entity;

/**
 * PelotaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PelotaRepository extends ProductRepository
{

}
