<?php

namespace LaFuente\PrestamoBundle\Entity;

/**
 * RaquetaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RaquetaRepository extends ProductRepository
{
}
