firmante_index:
    path:     /
    defaults: { _controller: "LaFuenteCertificadoBundle:Firmante:index" }
    methods:  GET

firmante_show:
    path:     /{id}/show
    defaults: { _controller: "LaFuenteCertificadoBundle:Firmante:show" }
    methods:  GET

firmante_new:
    path:     /new
    defaults: { _controller: "LaFuenteCertificadoBundle:Firmante:new" }
    methods:  [GET, POST]

firmante_edit:
    path:     /{id}/edit
    defaults: { _controller: "LaFuenteCertificadoBundle:Firmante:edit" }
    methods:  [GET, POST]

firmante_delete:
    path:     /{id}/delete
    defaults: { _controller: "LaFuenteCertificadoBundle:Firmante:delete" }
    methods:  DELETE
